workspace = { members = ["task"] }
[package]
name = "lexoterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
task = "0.0.1"
rand = "0.8"
ctrlc = "3.2"
catppuccin = "2.2.0"
